name: Actions Minutes Usage Check
on:
  workflow_dispatch:
  schedule:
    # - cron: '0 16 * * *' # 4PM UTC (11AM CST) Every day
    # - cron: '0 16 * * 1-5' # 4PM UTC (11AM CST) Only week days
    - cron: '*/5 * * * *' # Every 5 mins

jobs:
  actions-minutes-usage-check:
    runs-on: [ubuntu-latest]
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ALERT_USAGE_PERCENTAGE_THRESHOLD: 70
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      
      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Populate actions usage info
        id: usage
        run: |
          python populate_action_usage.py
          
      - name: Print actions usage info
        run: |
          echo "INCLUDED_MINUTES ${{ steps.usage.outputs.INCLUDED_MINUTES }}"
          echo "TOTAL_MINUTES_USED ${{ steps.usage.outputs.TOTAL_MINUTES_USED }}"
          echo "TOTAL_PAID_MINUTES_USED ${{ steps.usage.outputs.TOTAL_PAID_MINUTES_USED }}"
          echo "USAGE_PERCENTAGE ${{ steps.usage.outputs.USAGE_PERCENTAGE }}"
          
      - name: Send alert notifcation
        if: ${{ steps.usage.outputs.USAGE_PERCENTAGE }} > ${{ env.ALERT_USAGE_PERCENTAGE_THRESHOLD }} 
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message (https://api.slack.com/methods/chat.postMessage#channels)
          # Can pass multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: ":warning: GitHub Org (_${{ github.repository_owner }}_) Actions Minutes Usage is *${{ steps.usage.outputs.USAGE_PERCENTAGE }}%*.\nIncluded Minutes: *${{ steps.usage.outputs.INCLUDED_MINUTES }}*\nTotal Minutes Used: *${{ steps.usage.outputs.TOTAL_MINUTES_USED }}*\nTotal Paid Minutes Used: *${{ steps.usage.outputs.TOTAL_PAID_MINUTES_USED }}*"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}