name: Actions Usage Report
on:
  workflow_dispatch:
  schedule:
    - cron: '01 20 * * 1-5'

jobs:
  actions-usage-report:
    runs-on: [ubuntu-latest]
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      
      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Populate actions usage info
        id: usage
        run: |
          python populate_action_usage.py --user ${{ github.repository_owner }}
      - name: Print actions usage info
        run: |
          echo "TOTAL_MINUTES_USED ${{ steps.usage.outputs.TOTAL_MINUTES_USED }}"
          echo "INCLUDED_MINUTES ${{ steps.usage.outputs.INCLUDED_MINUTES }}"
          echo "USAGE_PERCENTAGE ${{ steps.usage.outputs.USAGE_PERCENTAGE }}"

      - name: Send notifcation
        if: ${{ steps.usage.outputs.USAGE_PERCENTAGE }} > 70
        run: |
          echo "Sending Notification as USAGE_PERCENTAGE (${{ steps.usage.outputs.USAGE_PERCENTAGE }}) is above 70"
          
      - name: Post to a Slack channel
        if: ${{ steps.usage.outputs.USAGE_PERCENTAGE }} > 70
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }} 
          # For posting a simple plain text message
          slack-message: "Sending Notification as USAGE_PERCENTAGE (${{ steps.usage.outputs.USAGE_PERCENTAGE }}) is above 70"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}